import os
import json
import torch
import torch.nn as nn
from transformers import AutoTokenizer, AutoModel
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW

# Configurations
MODEL_DIR = "../data/models"
# Keep generated model artifacts aligned with intents the app actually routes.
EXCLUDED_INTENTS = set()

# Define the Dataset for D&D, Game, and Basic Intents
# Using the BIO inline annotation format
intent_data = {

    "lookup_monster": [
        "can you tell me about the aboleth/B-monster_name",
        "what exactly is an acolyte/B-monster_name",
        "show me the stats for an adult/B-monster_name black/I-monster_name dragon/I-monster_name",
        "i want info on an air/B-monster_name elemental/I-monster_name",
        "what abilities does an ancient/B-monster_name red/I-monster_name dragon/I-monster_name have",
        "give me details about animated/B-monster_name armor/I-monster_name",
        "what is the androsphinx/B-monster_name like",
        "how strong is a bandit/B-monster_name captain/I-monster_name",
        "what does a behir/B-monster_name do in combat",
        "show stats for a black/B-monster_name pudding/I-monster_name",
        "what are the weaknesses of a chuul/B-monster_name",
        "i need info on a cult/B-monster_name fanatic/I-monster_name",
        "what are the stats for a doppelganger/B-monster_name",
        "can you explain a dust/B-monster_name mephit/I-monster_name",
        "how dangerous is a fire/B-monster_name giant/I-monster_name really",
        "give me the profile for a gelatinous/B-monster_name cube/I-monster_name",
        "what powers does a giant/B-monster_name constrictor/I-monster_name snake/I-monster_name have",
        "describe a flesh/B-monster_name golem/I-monster_name for me",
        "what kind of creature is a lich/B-monster_name",
        "show the attributes of a minotaur/B-monster_name skeleton/I-monster_name",
        "what is an otyugh/B-monster_name exactly",
        "give me details on a purple/B-monster_name worm/I-monster_name",
        "open the entry for a rug/B-monster_name of/I-monster_name smothering/I-monster_name",
        "what’s the armor class of a swarm/B-monster_name of/I-monster_name poisonous/I-monster_name snakes/I-monster_name",
        "can you pull up the tarrasque/B-monster_name",
        "what’s the challenge rating for a vampire/B-monster_name spawn/I-monster_name",
        "look up a treant/B-monster_name",
        "how many hit points does a zombie/B-monster_name have",
        "how fast can a young/B-monster_name brass/I-monster_name dragon/I-monster_name fly",
        "show me the stat block for a solar/B-monster_name",
        "fetch info on a stone/B-monster_name golem/I-monster_name",
        "i want the stat block for a spirit/B-monster_name naga/I-monster_name",
        "what immunities does a shambling/B-monster_name mound/I-monster_name have",
        "how does a rust/B-monster_name monster/I-monster_name attack",
        "show me lore about a rakshasa/B-monster_name",
        "what saving throws does a pit/B-monster_name fiend/I-monster_name have",
        "how does an owlbear/B-monster_name fight",
        "find info about a night/B-monster_name hag/I-monster_name",
        "i want to check a mummy/B-monster_name lord/I-monster_name",
        "what does a kraken/B-monster_name look like",
        "what languages can an iron/B-monster_name golem/I-monster_name speak",
        "show stats for a hill/B-monster_name giant/I-monster_name",
        "find the glabrezu/B-monster_name entry",
        "what’s the speed of a hippogriff/B-monster_name",
        "what resistances does a magma/B-monster_name mephit/I-monster_name have",
        "show the legendary actions of a mummy/B-monster_name lord/I-monster_name",
        "how many hit dice does a half-red/B-monster_name dragon/I-monster_name veteran/I-monster_name have",
        "what alignment is an invisible/B-monster_name stalker/I-monster_name",
        "describe a gray/B-monster_name ooze/I-monster_name",
        "what vulnerabilities does a hezrou/B-monster_name have"
    ],

    "lookup_spell": [
        "can you tell me about acid/B-spell_name arrow/I-spell_name",
        "what does aid/B-spell_name actually do",
        "show me the spell animal/B-spell_name friendship/I-spell_name",
        "i need info on antimagic/B-spell_name field/I-spell_name",
        "how does arcane/B-spell_name lock/I-spell_name work",
        "give me the stats for astral/B-spell_name projection/I-spell_name",
        "what are the effects of bane/B-spell_name",
        "can you explain barkskin/B-spell_name",
        "details on black/B-spell_name tentacles/I-spell_name",
        "pull up blade/B-spell_name barrier/I-spell_name",
        "what does blindness/deafness/B-spell_name do",
        "tell me about burning/B-spell_name hands/I-spell_name",
        "how does call/B-spell_name lightning/I-spell_name work",
        "what damage does chain/B-spell_name lightning/I-spell_name deal",
        "show me the description for charm/B-spell_name person/I-spell_name",
        "what is the range of chill/B-spell_name touch/I-spell_name",
        "i want info on circle/B-spell_name of/I-spell_name death/I-spell_name",
        "what kind of save is needed for cloudkill/B-spell_name",
        "look up color/B-spell_name spray/I-spell_name",
        "give me details about commune/B-spell_name with/I-spell_name nature/I-spell_name",
        "can you find comprehend/B-spell_name languages/I-spell_name",
        "how large is cone/B-spell_name of/I-spell_name cold/I-spell_name",
        "show me conjure/B-spell_name animals/I-spell_name",
        "what are the risks of contact/B-spell_name other/I-spell_name plane/I-spell_name",
        "explain control/B-spell_name weather/I-spell_name",
        "show stats for counterspell/B-spell_name",
        "how does create/B-spell_name food/I-spell_name and/I-spell_name water/I-spell_name work",
        "cure/B-spell_name wounds/I-spell_name details",
        "describe the spell dancing/B-spell_name lights/I-spell_name",
        "what’s the duration for darkvision/B-spell_name",
        "look up delayed/B-spell_name blast/I-spell_name fireball/I-spell_name",
        "tell me about detect/B-spell_name magic/I-spell_name",
        "how does dimension/B-spell_name door/I-spell_name function",
        "search for disintegrate/B-spell_name",
        "what is divine/B-spell_name word/I-spell_name",
        "show me dominate/B-spell_name monster/I-spell_name",
        "give me stats for eldritch/B-spell_name blast/I-spell_name",
        "what does faerie/B-spell_name fire/I-spell_name do",
        "feather/B-spell_name fall/I-spell_name info",
        "explain finger/B-spell_name of/I-spell_name death/I-spell_name",
        "fireball/B-spell_name details",
        "how does floating/B-spell_name disk/I-spell_name work",
        "show the entry for gaseous/B-spell_name form/I-spell_name",
        "find greater/B-spell_name invisibility/I-spell_name",
        "how do i use guiding/B-spell_name bolt/I-spell_name",
        "healing/B-spell_name word/I-spell_name stats",
        "what happens when you cast heat/B-spell_name metal/I-spell_name",
        "look up hunter's/B-spell_name mark/I-spell_name",
        "tell me about magic/B-spell_name missile/I-spell_name",
        "what’s the range of misty/B-spell_name step/I-spell_name"
    ],

    "lookup_equipment_category": [
        "show me adventuring/B-category_name gear/I-category_name",
        "list all ammunition/B-category_name",
        "what are arcane/B-category_name foci/I-category_name",
        "i want to see armor/B-category_name",
        "tell me about artisan's/B-category_name tools/I-category_name",
        "what counts as druidic/B-category_name foci/I-category_name",
        "show equipment/B-category_name packs/I-category_name",
        "find gaming/B-category_name sets/I-category_name",
        "display heavy/B-category_name armor/I-category_name",
        "give me info on holy/B-category_name symbols/I-category_name",
        "what is included in kits/B-category_name",
        "list land/B-category_name vehicles/I-category_name",
        "show light/B-category_name armor/I-category_name",
        "find martial/B-category_name melee/I-category_name weapons/I-category_name",
        "what are martial/B-category_name ranged/I-category_name weapons/I-category_name",
        "show martial/B-category_name weapons/I-category_name",
        "details on medium/B-category_name armor/I-category_name",
        "look up melee/B-category_name weapons/I-category_name",
        "show mounts/B-category_name and/I-category_name other/I-category_name animals/I-category_name",
        "explain mounts/B-category_name and/I-category_name vehicles/I-category_name",
        "i want musical/B-category_name instruments/I-category_name",
        "check other/B-category_name tools/I-category_name",
        "show potion/B-category_name category",
        "list ranged/B-category_name weapons/I-category_name",
        "open ring/B-category_name category",
        "what items are under rod/B-category_name",
        "show scroll/B-category_name types",
        "what are shields/B-category_name",
        "show simple/B-category_name melee/I-category_name weapons/I-category_name",
        "list simple/B-category_name ranged/I-category_name weapons/I-category_name",
        "look up simple/B-category_name weapons/I-category_name",
        "what is in staff/B-category_name",
        "tell me about standard/B-category_name gear/I-category_name",
        "show tack,/B-category_name harness,/I-category_name and/I-category_name drawn/I-category_name vehicles/I-category_name",
        "explain tools/B-category_name category",
        "show wand/B-category_name list",
        "list waterborne/B-category_name vehicles/I-category_name",
        "tell me about weapon/B-category_name category",
        "what are wondrous/B-category_name items/I-category_name",
        "help me find adventuring/B-category_name gear/I-category_name",
        "open ammunition/B-category_name section",
        "show artisan's/B-category_name tools/I-category_name",
        "display light/B-category_name armor/I-category_name",
        "find musical/B-category_name instruments/I-category_name",
        "what potion/B-category_name items are there",
        "search martial/B-category_name melee/I-category_name weapons/I-category_name",
        "show wondrous/B-category_name items/I-category_name",
        "open kits/B-category_name category",
        "i need waterborne/B-category_name vehicles/I-category_name",
        "list simple/B-category_name weapons/I-category_name"
    ],

    "lookup_weapon_property": [
        "what does the ammunition/B-property_name property mean",
        "explain finesse/B-property_name",
        "how do heavy/B-property_name weapons work",
        "define the light/B-property_name property",
        "how does loading/B-property_name work",
        "what are monk/B-property_name weapons",
        "what does reach/B-property_name do",
        "explain the special/B-property_name property",
        "how do thrown/B-property_name weapons behave",
        "what does two-handed/B-property_name require",
        "describe the versatile/B-property_name property",
        "look up ammunition/B-property_name rules",
        "what are the finesse/B-property_name rules",
        "can small creatures use heavy/B-property_name weapons",
        "rules for light/B-property_name weapons",
        "explain loading/B-property_name property",
        "details about monk/B-property_name weapons",
        "how far does reach/B-property_name extend",
        "what is special/B-property_name in weapons",
        "can i attack in melee with thrown/B-property_name weapons",
        "do i need two hands for two-handed/B-property_name weapons",
        "how does versatile/B-property_name damage work",
        "what is the ammunition/B-property_name tag",
        "does finesse/B-property_name allow dexterity",
        "find info on heavy/B-property_name property",
        "can i dual wield light/B-property_name weapons",
        "how many attacks with loading/B-property_name",
        "what qualifies as monk/B-property_name weapons",
        "check reach/B-property_name rules",
        "why is a weapon special/B-property_name",
        "what is the range for thrown/B-property_name",
        "two-handed/B-property_name mechanics",
        "one hand vs two hand versatile/B-property_name",
        "tell me about finesse/B-property_name",
        "look up reach/B-property_name",
        "explain versatile/B-property_name",
        "how does ammunition/B-property_name work",
        "heavy/B-property_name disadvantages",
        "is this weapon light/B-property_name",
        "loading/B-property_name details",
        "monk/B-property_name weapon rules",
        "what is reach/B-property_name distance",
        "special/B-property_name weapon rules",
        "thrown/B-property_name mechanics",
        "two-handed/B-property_name explained",
        "versatile/B-property_name damage dice",
        "ammunition/B-property_name rules dnd",
        "finesse/B-property_name explanation",
        "search heavy/B-property_name",
        "what are light/B-property_name rules"
    ],

    "lookup_equipment": [
        "can you tell me about breastplate/B-equipment_name",
        "what is the ac of chain/B-equipment_name mail/I-equipment_name",
        "how much does leather/B-equipment_name armor/I-equipment_name cost",
        "show me the stats for half/B-equipment_name plate/I-equipment_name armor/I-equipment_name",
        "how does hide/B-equipment_name armor/I-equipment_name work",
        "look up plate/B-equipment_name armor/I-equipment_name",
        "give me details on scale/B-equipment_name mail/I-equipment_name",
        "what does a shield/B-equipment_name provide",
        "describe padded/B-equipment_name armor/I-equipment_name",
        "find ring/B-equipment_name mail/I-equipment_name",
        "tell me about splint/B-equipment_name armor/I-equipment_name",
        "show me studded/B-equipment_name leather/I-equipment_name armor/I-equipment_name",
        "what are the stats for chain/B-equipment_name shirt/I-equipment_name",
        "what properties does a longsword/B-equipment_name have",
        "look up dungeoneer's/B-equipment_name pack/I-equipment_name",
        "tell me about a backpack/B-equipment_name",
        "what comes in a burglar's/B-equipment_name pack/I-equipment_name",
        "how heavy is a crowbar/B-equipment_name",
        "show me the stats for a dagger/B-equipment_name",
        "describe an explorer's/B-equipment_name pack/I-equipment_name",
        "what does a grappling/B-equipment_name hook/I-equipment_name do",
        "show me a greataxe/B-equipment_name",
        "give me details on a greatsword/B-equipment_name",
        "what is a holy/B-equipment_name water/I-equipment_name flask/I-equipment_name",
        "find lantern/B-equipment_name bullseye/I-equipment_name",
        "look up longbow/B-equipment_name",
        "what are the stats of a mace/B-equipment_name",
        "explain the magnifying/B-equipment_name glass/I-equipment_name",
        "tell me about manacles/B-equipment_name",
        "what is a mess/B-equipment_name kit/I-equipment_name",
        "show me pick/B-equipment_name miner's/I-equipment_name",
        "what does a portable/B-equipment_name ram/I-equipment_name do",
        "find a rapier/B-equipment_name",
        "look up silk/B-equipment_name rope/I-equipment_name",
        "explain scimitar/B-equipment_name",
        "tell me about a shortbow/B-equipment_name",
        "show me the stats for a shortsword/B-equipment_name",
        "what is a spellbook/B-equipment_name",
        "describe a spyglass/B-equipment_name",
        "tell me about thieves'/B-equipment_name tools/I-equipment_name",
        "what is a tinderbox/B-equipment_name",
        "look up a warhammer/B-equipment_name",
        "show me a waterskin/B-equipment_name",
        "give me details on a whip/B-equipment_name",
        "what is woodcarver's/B-equipment_name tools/I-equipment_name",
        "look up barding:/B-equipment_name plate/I-equipment_name",
        "how much does barding:/B-equipment_name leather/I-equipment_name cost",
        "find barding:/B-equipment_name chain/I-equipment_name mail/I-equipment_name",
        "give me info on barding:/B-equipment_name hide/I-equipment_name",
        "explain barding:/B-equipment_name studded/I-equipment_name leather/I-equipment_name"
    ],

    "lookup_class": [
        "can you tell me about the barbarian/B-class_name",
        "what are the main features of a bard/B-class_name",
        "show me the cleric/B-class_name class table",
        "how does a druid/B-class_name play",
        "i want to build a fighter/B-class_name",
        "what abilities do monks/B-class_name have",
        "explain the paladin/B-class_name class",
        "what spells does a ranger/B-class_name get",
        "what proficiencies does a rogue/B-class_name have",
        "tell me about the sorcerer/B-class_name",
        "what is a warlock/B-class_name like",
        "wizard/B-class_name details",
        "how many hit points does a barbarian/B-class_name get",
        "what domains can a cleric/B-class_name choose",
        "how does bard/B-class_name inspiration work",
        "is a druid/B-class_name beginner friendly",
        "what fighting styles does a fighter/B-class_name have",
        "how do monk/B-class_name ki points work",
        "what oaths does a paladin/B-class_name have",
        "how does ranger/B-class_name favored enemy work",
        "what is rogue/B-class_name sneak attack",
        "what metamagic options does a sorcerer/B-class_name have",
        "what invocations does a warlock/B-class_name get",
        "how does a wizard/B-class_name spellbook work",
        "look up barbarian/B-class_name",
        "show bard/B-class_name info",
        "give me details on cleric/B-class_name",
        "explain druid/B-class_name",
        "fighter/B-class_name stats",
        "monk/B-class_name level progression",
        "paladin/B-class_name smite mechanics",
        "ranger/B-class_name subclasses",
        "rogue/B-class_name archetypes",
        "sorcerer/B-class_name bloodlines",
        "warlock/B-class_name pact boons",
        "wizard/B-class_name traditions",
        "what hit die does a barbarian/B-class_name use",
        "show me the bard/B-class_name spell list",
        "what saving throws does a cleric/B-class_name have",
        "how does druid/B-class_name wild shape work",
        "what is fighter/B-class_name second wind",
        "monk/B-class_name unarmored defense explanation",
        "how does paladin/B-class_name lay on hands work",
        "what is ranger/B-class_name primeval awareness",
        "explain rogue/B-class_name cunning action",
        "how does sorcerer/B-class_name font of magic work",
        "what spell slots does a warlock/B-class_name have",
        "how does wizard/B-class_name ritual casting work",
        "tell me about rogue/B-class_name",
        "search for paladin/B-class_name"
    ],

    "lookup_race": [
        "can you tell me about the dragonborn/B-race_name",
        "what traits do dwarves/B-race_name have",
        "show me elf/B-race_name subraces",
        "how fast is a gnome/B-race_name",
        "what are the stats for a half-elf/B-race_name",
        "what abilities does a half-orc/B-race_name have",
        "describe the halfling/B-race_name race",
        "give me info on humans/B-race_name",
        "what is a tiefling/B-race_name like",
        "what is the dragonborn/B-race_name breath weapon",
        "explain dwarf/B-race_name stonecunning",
        "do elf/B-race_name characters sleep",
        "what is gnome/B-race_name darkvision range",
        "how does half-elf/B-race_name skill versatility work",
        "what is half-orc/B-race_name relentless endurance",
        "what does halfling/B-race_name lucky trait do",
        "what bonuses do humans/B-race_name get",
        "what is tiefling/B-race_name hellish resistance",
        "look up dwarf/B-race_name",
        "tell me about half-orc/B-race_name",
        "what are the features of a halfling/B-race_name",
        "i want info on dragonborn/B-race_name",
        "explain half-elf/B-race_name racial bonuses",
        "what is gnome/B-race_name cunning",
        "what weapons do elf/B-race_name get",
        "show me human/B-race_name traits",
        "explain tiefling/B-race_name infernal legacy",
        "what is the average height of a dwarf/B-race_name",
        "how long do elf/B-race_name live",
        "what is half-orc/B-race_name savage attacks",
        "can halfling/B-race_name hide behind others",
        "what resistances do dragonborn/B-race_name have",
        "is half-elf/B-race_name good for charisma",
        "what can gnome/B-race_name tinkerer do",
        "what are human/B-race_name variant rules",
        "what modifiers do tiefling/B-race_name get",
        "search for elf/B-race_name",
        "look up half-orc/B-race_name",
        "what are dragonborn/B-race_name stats",
        "describe a gnome/B-race_name",
        "what subraces do halfling/B-race_name have",
        "what proficiencies do dwarf/B-race_name get",
        "what languages do humans/B-race_name speak",
        "what do tiefling/B-race_name horns look like",
        "what is the age range of a half-elf/B-race_name",
        "what are the stats for a half-orc/B-race_name",
        "is a halfling/B-race_name small",
        "what perception bonus do elf/B-race_name get",
        "what is dragonborn/B-race_name draconic ancestry",
        "tell me about gnome/B-race_name"
        ],

    "lookup_condition": [
        "what happens if i am blinded/B-condition_name",
        "tell me about the charmed/B-condition_name condition",
        "can a deafened/B-condition_name creature still hear anything",
        "how does exhaustion/B-condition_name work",
        "what does frightened/B-condition_name do",
        "what are the rules for being grappled/B-condition_name",
        "what does incapacitated/B-condition_name mean",
        "what benefits does invisible/B-condition_name give",
        "how does paralyzed/B-condition_name affect a character",
        "what happens when a creature is petrified/B-condition_name",
        "what are the effects of poisoned/B-condition_name",
        "how does prone/B-condition_name work",
        "describe the restrained/B-condition_name condition",
        "what can a stunned/B-condition_name creature do",
        "is an unconscious/B-condition_name creature dying",
        "look up blinded/B-condition_name",
        "search charmed/B-condition_name condition",
        "show me deafened/B-condition_name rules",
        "what happens at exhaustion/B-condition_name level 1",
        "how do frightened/B-condition_name saves work",
        "how can i escape being grappled/B-condition_name",
        "explain incapacitated/B-condition_name",
        "does invisible/B-condition_name give advantage",
        "what are the effects of paralyzed/B-condition_name",
        "how does petrified/B-condition_name affect movement",
        "what disadvantage does poisoned/B-condition_name give",
        "how do you stand up from prone/B-condition_name",
        "what penalties come with restrained/B-condition_name",
        "does stunned/B-condition_name auto fail saves",
        "what happens when unconscious/B-condition_name",
        "give me info on blinded/B-condition_name",
        "what is charmed/B-condition_name effect",
        "look up deafened/B-condition_name",
        "tell me about exhaustion/B-condition_name levels",
        "what does frightened/B-condition_name do in combat",
        "rules for grappled/B-condition_name",
        "what happens when incapacitated/B-condition_name",
        "what does invisible/B-condition_name do exactly",
        "paralyzed/B-condition_name effects",
        "details on petrified/B-condition_name",
        "poisoned/B-condition_name mechanics",
        "prone/B-condition_name explanation",
        "restrained/B-condition_name rules",
        "stunned/B-condition_name summary",
        "unconscious/B-condition_name condition info",
        "am i blinded/B-condition_name in darkness",
        "can i move while grappled/B-condition_name",
        "does invisible/B-condition_name mean hidden",
        "what happens at exhaustion/B-condition_name level 3",
        "what is prone/B-condition_name"
        ],

    "lookup_magic-schools": [
        "what is abjuration/B-magic_school",
        "can you explain conjuration/B-magic_school",
        "tell me about divination/B-magic_school magic",
        "what does enchantment/B-magic_school mean",
        "how does evocation/B-magic_school work",
        "what is illusion/B-magic_school",
        "explain necromancy/B-magic_school",
        "what is transmutation/B-magic_school",
        "give me info on abjuration/B-magic_school spells",
        "what kind of spells are conjuration/B-magic_school",
        "what does divination/B-magic_school focus on",
        "what is enchantment/B-magic_school used for",
        "what does evocation/B-magic_school specialize in",
        "what defines illusion/B-magic_school magic",
        "what is necromancy/B-magic_school about",
        "what does transmutation/B-magic_school do",
        "show me abjuration/B-magic_school",
        "look up conjuration/B-magic_school",
        "search for divination/B-magic_school",
        "open enchantment/B-magic_school",
        "find evocation/B-magic_school",
        "show illusion/B-magic_school details",
        "look up necromancy/B-magic_school",
        "search transmutation/B-magic_school",
        "abjuration/B-magic_school explanation",
        "conjuration/B-magic_school details",
        "divination/B-magic_school info",
        "enchantment/B-magic_school description",
        "evocation/B-magic_school meaning",
        "illusion/B-magic_school overview",
        "necromancy/B-magic_school summary",
        "transmutation/B-magic_school basics",
        "what spells belong to abjuration/B-magic_school",
        "which spells are conjuration/B-magic_school",
        "what counts as divination/B-magic_school",
        "what spells use enchantment/B-magic_school",
        "which spells are evocation/B-magic_school",
        "what spells are illusion/B-magic_school",
        "what spells fall under necromancy/B-magic_school",
        "what spells are transmutation/B-magic_school",
        "what is the purpose of abjuration/B-magic_school",
        "how is conjuration/B-magic_school used",
        "what is divination/B-magic_school good for",
        "what does enchantment/B-magic_school affect",
        "what kind of magic is evocation/B-magic_school",
        "what is illusion/B-magic_school known for",
        "what does necromancy/B-magic_school deal with",
        "what is transmutation/B-magic_school focused on",
        "explain abjuration/B-magic_school spells",
        "describe conjuration/B-magic_school magic",
        "divination/B-magic_school what does it do",
        "enchantment/B-magic_school effects explanation",
        "evocation/B-magic_school spell type",
        "illusion/B-magic_school magic explanation",
        "necromancy/B-magic_school meaning",
        "transmutation/B-magic_school definition",
        "is abjuration/B-magic_school defensive",
        "does conjuration/B-magic_school summon things",
        "is divination/B-magic_school about foresight",
        "does enchantment/B-magic_school control minds",
        "is evocation/B-magic_school damage based",
        "does illusion/B-magic_school create fake images",
        "is necromancy/B-magic_school about life and death",
        "does transmutation/B-magic_school change matter"
        ],

    "lookup_traits": [
        "what is artificer's/B-trait_name lore/I-trait_name",
        "can you explain brave/B-trait_name",
        "what does breath/B-trait_name weapon/I-trait_name do",
        "tell me about damage/B-trait_name resistance/I-trait_name",
        "how does darkvision/B-trait_name work",
        "what is draconic/B-trait_name ancestry/I-trait_name",
        "explain draconic/B-trait_name ancestry/I-trait_name (Black)/I-trait_name",
        "what does draconic/B-trait_name ancestry/I-trait_name (Blue)/I-trait_name do",
        "tell me about draconic/B-trait_name ancestry/I-trait_name (Brass)/I-trait_name",
        "how does draconic/B-trait_name ancestry/I-trait_name (Bronze)/I-trait_name work",
        "what is draconic/B-trait_name ancestry/I-trait_name (Copper)/I-trait_name",
        "explain draconic/B-trait_name ancestry/I-trait_name (Gold)/I-trait_name",
        "what does draconic/B-trait_name ancestry/I-trait_name (Green)/I-trait_name mean",
        "tell me about draconic/B-trait_name ancestry/I-trait_name (Red)/I-trait_name",
        "what is draconic/B-trait_name ancestry/I-trait_name (Silver)/I-trait_name",
        "how does draconic/B-trait_name ancestry/I-trait_name (White)/I-trait_name work",
        "what is dwarven/B-trait_name combat/I-trait_name training/I-trait_name",
        "tell me about dwarven/B-trait_name resilience/I-trait_name",
        "what does dwarven/B-trait_name toughness/I-trait_name do",
        "explain elf/B-trait_name weapon/I-trait_name training/I-trait_name",
        "what is extra/B-trait_name language/I-trait_name",
        "how does fey/B-trait_name ancestry/I-trait_name work",
        "what does gnome/B-trait_name cunning/I-trait_name do",
        "tell me about halfling/B-trait_name nimbleness/I-trait_name",
        "what is hellish/B-trait_name resistance/I-trait_name",
        "how does high/B-trait_name elf/I-trait_name cantrip/I-trait_name work",
        "explain infernal/B-trait_name legacy/I-trait_name",
        "what does keen/B-trait_name senses/I-trait_name do",
        "tell me about lucky/B-trait_name",
        "what is menacing/B-trait_name",
        "how does naturally/B-trait_name stealthy/I-trait_name work",
        "what does relentless/B-trait_name endurance/I-trait_name do",
        "tell me about savage/B-trait_name attacks/I-trait_name",
        "what is skill/B-trait_name versatility/I-trait_name",
        "explain stonecunning/B-trait_name",
        "how does tinker/B-trait_name work",
        "what is tool/B-trait_name proficiency/I-trait_name",
        "tell me about trance/B-trait_name",
        "show me artificer's/B-trait_name lore/I-trait_name",
        "look up brave/B-trait_name",
        "search for breath/B-trait_name weapon/I-trait_name",
        "open damage/B-trait_name resistance/I-trait_name",
        "find darkvision/B-trait_name",
        "show draconic/B-trait_name ancestry/I-trait_name",
        "look up draconic/B-trait_name ancestry/I-trait_name (Black)/I-trait_name",
        "search draconic/B-trait_name ancestry/I-trait_name (Blue)/I-trait_name",
        "open draconic/B-trait_name ancestry/I-trait_name (Brass)/I-trait_name",
        "find draconic/B-trait_name ancestry/I-trait_name (Bronze)/I-trait_name",
        "show draconic/B-trait_name ancestry/I-trait_name (Copper)/I-trait_name details",
        "look up draconic/B-trait_name ancestry/I-trait_name (Gold)/I-trait_name",
        "search draconic/B-trait_name ancestry/I-trait_name (Green)/I-trait_name",
        "open draconic/B-trait_name ancestry/I-trait_name (Red)/I-trait_name",
        "find draconic/B-trait_name ancestry/I-trait_name (Silver)/I-trait_name",
        "show draconic/B-trait_name ancestry/I-trait_name (White)/I-trait_name",
        "look up dwarven/B-trait_name combat/I-trait_name training/I-trait_name",
        "search dwarven/B-trait_name resilience/I-trait_name",
        "open dwarven/B-trait_name toughness/I-trait_name",
        "find elf/B-trait_name weapon/I-trait_name training/I-trait_name",
        "show extra/B-trait_name language/I-trait_name",
        "look up fey/B-trait_name ancestry/I-trait_name",
        "search gnome/B-trait_name cunning/I-trait_name",
        "open halfling/B-trait_name nimbleness/I-trait_name",
        "find hellish/B-trait_name resistance/I-trait_name",
        "show high/B-trait_name elf/I-trait_name cantrip/I-trait_name",
        "look up infernal/B-trait_name legacy/I-trait_name",
        "search keen/B-trait_name senses/I-trait_name",
        "open lucky/B-trait_name",
        "find menacing/B-trait_name",
        "show naturally/B-trait_name stealthy/I-trait_name",
        "look up relentless/B-trait_name endurance/I-trait_name",
        "search savage/B-trait_name attacks/I-trait_name",
        "open skill/B-trait_name versatility/I-trait_name",
        "find stonecunning/B-trait_name",
        "show tinker/B-trait_name",
        "look up tool/B-trait_name proficiency/I-trait_name",
        "search trance/B-trait_name",
        "artificer's/B-trait_name lore/I-trait_name explanation",
        "brave/B-trait_name details",
        "breath/B-trait_name weapon/I-trait_name info",
        "damage/B-trait_name resistance/I-trait_name meaning",
        "darkvision/B-trait_name range explanation",
        "draconic/B-trait_name ancestry/I-trait_name overview",
        "dwarven/B-trait_name resilience/I-trait_name details",
        "fey/B-trait_name ancestry/I-trait_name explanation",
        "gnome/B-trait_name cunning/I-trait_name info",
        "halfling/B-trait_name nimbleness/I-trait_name summary",
        "hellish/B-trait_name resistance/I-trait_name details",
        "infernal/B-trait_name legacy/I-trait_name explanation",
        "keen/B-trait_name senses/I-trait_name meaning",
        "relentless/B-trait_name endurance/I-trait_name details",
        "savage/B-trait_name attacks/I-trait_name explanation",
        "skill/B-trait_name versatility/I-trait_name info",
        "stonecunning/B-trait_name summary",
        "tool/B-trait_name proficiency/I-trait_name details",
        "trance/B-trait_name explanation",
        "what does brave/B-trait_name protect against",
        "how far can darkvision/B-trait_name see",
        "what damage type comes with draconic/B-trait_name ancestry/I-trait_name (Red)/I-trait_name",
        "what resistance does draconic/B-trait_name ancestry/I-trait_name (White)/I-trait_name give",
        "does dwarven/B-trait_name resilience/I-trait_name give advantage",
        "what weapons come from elf/B-trait_name weapon/I-trait_name training/I-trait_name",
        "how many languages does extra/B-trait_name language/I-trait_name give",
        "does fey/B-trait_name ancestry/I-trait_name help against charm",
        "what saves does gnome/B-trait_name cunning/I-trait_name affect",
        "how does halfling/B-trait_name nimbleness/I-trait_name help movement",
        "what damage does hellish/B-trait_name resistance/I-trait_name reduce",
        "what can you cast with high/B-trait_name elf/I-trait_name cantrip/I-trait_name",
        "what spells come from infernal/B-trait_name legacy/I-trait_name",
        "does keen/B-trait_name senses/I-trait_name give proficiency",
        "how does lucky/B-trait_name work on a roll",
        "what does menacing/B-trait_name grant",
        "how do you use naturally/B-trait_name stealthy/I-trait_name",
        "what happens when relentless/B-trait_name endurance/I-trait_name triggers",
        "does savage/B-trait_name attacks/I-trait_name add damage",
        "how many skills does skill/B-trait_name versatility/I-trait_name give",
        "what checks use stonecunning/B-trait_name",
        "what can you build with tinker/B-trait_name",
        "what tools does tool/B-trait_name proficiency/I-trait_name give",
        "do elves rest with trance/B-trait_name instead of sleep"
        ],

    "move": [
        "move north/B-direction",
        "go south/B-direction",
        "walk east/B-direction",
        "head west/B-direction",
        "run north/B-direction",
        "travel south/B-direction",
        "step east/B-direction",
        "move towards west/B-direction",
        "go up/B-direction",
        "go down/B-direction",
        "head north/B-direction quickly",
        "walk south/B-direction slowly",
        "proceed east/B-direction",
        "advance north/B-direction",
        "continue south/B-direction",
        "go straight east/B-direction",
        "turn west/B-direction",
        "move north/B-direction now",
        "quickly go south/B-direction",
        "slowly head east/B-direction",
        "proceed to the north/B-direction",
        "walk toward south/B-direction",
        "move east/B-direction immediately",
        "north/B-direction",
        "south/B-direction",
        "east/B-direction",
        "west/B-direction",
        "up/B-direction",
        "down/B-direction"
    ],

    "attack": [
        "attack the goblin/B-monster_name",
        "hit the goblin/B-monster_name",
        "kill the goblin/B-monster_name",
        "strike the monster/B-monster_name",
        "fight the goblin/B-monster_name",
        "slash the enemy/B-monster_name",
        "stab the goblin/B-monster_name",
        "take down the monster/B-monster_name",
        "finish off the goblin/B-monster_name",
        "deal damage to the monster/B-monster_name",
        "attack that goblin/B-monster_name now",
        "swing at the enemy/B-monster_name",
        "smash the monster/B-monster_name",
        "fight the enemy/B-monster_name with my weapon",
        "go attack the goblin/B-monster_name",
        "hit the monster/B-monster_name hard",
        "strike the goblin/B-monster_name again",
        "attack the enemy/B-monster_name with the axe",
        "slay the goblin/B-monster_name",
        "stab the monster/B-monster_name now",
        "fight the goblin/B-monster_name right away",
        "attack the monster/B-monster_name in front of me",
        "attack it/B-monster_name",
        "hit it/B-monster_name",
        "fight it/B-monster_name"
    ],

    "inspect_room": [
        "look around",
        "inspect the room",
        "search the room",
        "what is in here",
        "what do i see",
        "scan the area",
        "check the room",
        "show me the room",
        "examine the room",
        "look around the dungeon",
        "tell me what is nearby",
        "what is around me",
        "inspect my surroundings",
        "search this area",
        "do a room check",
        "take a look around",
        "show nearby objects",
        "what is here",
        "give me the room details",
        "examine my surroundings",
        "scan this room",
        "tell me what is in the area"
    ],

    "open_object": [
        "open the chest/B-object_name",
        "unlock the chest/B-object_name",
        "open the treasure/B-object_name chest/I-object_name",
        "unlock the treasure/B-object_name chest/I-object_name",
        "open the treasure/B-object_name",
        "use the key on the chest/B-object_name",
        "open that chest/B-object_name",
        "unlock that chest/B-object_name",
        "open the locked chest/B-object_name",
        "unlock the locked chest/B-object_name",
        "open the treasure/B-object_name box/I-object_name",
        "use the rusty key on the chest/B-object_name",
        "can i open the chest/B-object_name",
        "let me open the treasure/B-object_name chest/I-object_name",
        "try to open the chest/B-object_name",
        "open up the chest/B-object_name",
        "unlock the treasure/B-object_name",
        "open the loot/B-object_name chest/I-object_name",
        "use my key on the treasure/B-object_name chest/I-object_name",
        "open the prize/B-object_name chest/I-object_name",
        "unlock this chest/B-object_name",
        "open the big chest/B-object_name"
    ],

    "pick_up": [
        "pick up the sword/B-item_name",
        "grab the key/B-item_name",
        "take the health/B-item_name potion/I-item_name",
        "collect the shield/B-item_name",
        "pick up gold/B-item_name coins/I-item_name",
        "grab the magic/B-item_name scroll/I-item_name",
        "take the dagger/B-item_name",
        "loot the chest/B-item_name",
        "pick up the armor/B-item_name",
        "grab a mana/B-item_name potion/I-item_name",
        "take the ring/B-item_name",
        "collect the treasure/B-item_name",
        "pick up the helmet/B-item_name",
        "grab the boots/B-item_name",
        "take the staff/B-item_name",
        "collect the gem/B-item_name",
        "pick up arrows/B-item_name",
        "grab the bow/B-item_name",
        "take the potion/B-item_name",
        "collect coins/B-item_name",
        "pick up the artifact/B-item_name",
        "grab the loot/B-item_name",
        "take potion/B-item_name",
        "pick up potion/B-item_name",
        "grab potion/B-item_name",
        "take the key/B-item_name"
    ],

    "use_item": [
        "use a potion/B-item_name",
        "drink the health/B-item_name potion/I-item_name",
        "drink the potion/B-item_name",
        "use the potion/B-item_name",
        "use the key/B-item_name",
        "consume a mana/B-item_name potion/I-item_name",
        "consume the potion/B-item_name",
        "take the potion/B-item_name",
        "activate the scroll/B-item_name",
        "equip the sword/B-item_name",
        "wear the armor/B-item_name",
        "use the shield/B-item_name",
        "drink the elixir/B-item_name",
        "apply the bandage/B-item_name",
        "use the magic/B-item_name ring/I-item_name",
        "equip the helmet/B-item_name",
        "use the boots/B-item_name",
        "activate the artifact/B-item_name",
        "apply the potion/B-item_name",
        "activate the amulet/B-item_name",
        "use the scroll/B-item_name now",
        "drink potion/B-item_name",
        "use potion/B-item_name",
        "take potion/B-item_name",
        "quaff the potion/B-item_name"
    ],

    "equip_item": [
        "equip the sword/B-item_name",
        "switch to the axe/B-item_name",
        "equip the dagger/B-item_name",
        "wield the sword/B-item_name",
        "draw the battle/B-item_name axe/I-item_name",
        "equip the iron/B-item_name sword/I-item_name",
        "switch weapons to the axe/B-item_name",
        "take the sword/B-item_name",
        "put on the armor/B-item_name",
        "equip my weapon/B-item_name",
        "switch to my sword/B-item_name",
        "equip the battle/B-item_name axe/I-item_name",
        "draw the dagger/B-item_name",
        "wield the axe/B-item_name",
        "switch my gear to the sword/B-item_name",
        "equip the larger weapon/B-item_name",
        "change weapon to the axe/B-item_name",
        "ready the sword/B-item_name",
        "take up the dagger/B-item_name",
        "outfit myself with the sword/B-item_name"
    ],

    "show_inventory": [
        "show my inventory",
        "what am i carrying",
        "list my items",
        "show my items",
        "what is in my inventory",
        "check my inventory",
        "show what i have",
        "what am i holding",
        "list my gear",
        "display my inventory",
        "what items do i have",
        "show me what i am carrying",
        "tell me my inventory",
        "what do i have with me",
        "show my current items",
        "list everything i am carrying",
        "check what i have",
        "display my items",
        "show all my gear",
        "what is in my pack"
    ],

    "show_status": [
        "show my status",
        "what is my status",
        "show my health",
        "tell me my stats",
        "what is my current health",
        "show my current status",
        "what is my hp",
        "tell me my position",
        "show my weapon",
        "give me my status",
        "what is the dungeon status",
        "tell me where i am",
        "show my condition",
        "check my status",
        "display my stats",
        "what weapon am i holding",
        "tell me my health points",
        "show my current position",
        "what is my situation",
        "give me a status report"
    ],

    "restart_game": [
        "restart the game",
        "start over",
        "reset the dungeon",
        "restart everything",
        "begin a new game",
        "reset the game",
        "start a new run",
        "wipe progress and restart",
        "reboot the game",
        "restart from the beginning",
        "reset all progress",
        "start fresh",
        "restart the whole game",
        "start the game again",
        "reset my progress",
        "clear everything and restart",
        "begin from scratch",
        "restart the level",
        "reload the game from start",
        "reset the adventure",
        "restart the session",
        "start the dungeon again"
    ],

    "Greetings": [
        "hello",
        "hi",
        "hey",
        "good morning",
        "good evening",
        "hello there",
        "hi assistant",
        "hey there",
        "good afternoon",
        "hello assistant",
        "hi there",
        "hey assistant",
        "good day",
        "hello again",
        "hi again",

        # Basic & Informal
        "Hey!",
        "Hi there.",
        "Howdy!",
        "Yo.",
        "Hi hi.",

        # Time-based
        "Good morning, how are you?",
        "Good afternoon, assistant.",
        "A very good evening to you.",
        "Good day.",
        "Morning!",

        # Conversational/Check-ins
        "How's it going today?",
        "What's up?",
        "How's everything?",
        "How are things?",
        "Nice to see you.",
        "Hey, how've you been?",
        "What's new?",
        "How are you doing this morning?",

        # Formal/Polite
        "Greetings.",
        "Hello, I hope you're having a good day.",
        "Hello, it's nice to speak with you.",
        "I'd like to say hello.",
        "Pleasure to meet you.",

        # Returns/Again
        "Hello again.",
        "Hi, I'm back.",
        "Hey there, me again.",
        "Good to see you again.",

        # Compound Greetings
        "Hey, quick question for you.",
        "Hi assistant, can you help me?",
        "Hello, are you there?",
        "Hi, I need a hand with something."
    ],
    "Goodbye": [
        "bye",
        "goodbye",
        "see you",
        "talk to you later",
        "bye bye",
        "see you later",
        "good night",
        "catch you later",
        "farewell",
        "see you soon",
        "bye for now",
        "talk later",
        "have a good night",
        "goodbye assistant",
        "see you next time",

        # Short & Informal
        "Bye!",
        "Peace.",
        "Later.",
        "Bye bye.",
        "I'm out.",
        "Cya.",

        # Time-based Goodbyes
        "Good night.",
        "Have a great evening.",
        "Enjoy the rest of your day.",
        "Have a good weekend.",
        "Have a nice afternoon.",
        "Sleep well.",

        # Future-focused (See you...)
        "See you later.",
        "Catch you on the flip side.",
        "Talk to you soon.",
        "See ya in a bit.",
        "Talk to you next time.",
        "I'll catch you later.",
        "Until next time.",

        # Formal/Polite
        "Goodbye.",
        "Farewell.",
        "Take care.",
        "I'm heading out now, goodbye.",
        "I'm finished for today, thank you.",
        "It was nice talking to you.",
        "I'll be going now.",

        # Conversational "Sign-offs"
        "That's all I needed, thanks!",
        "I'm done here, bye.",
        "Okay, talk to you later then.",
        "Alright, see you.",
        "Thanks for the help, goodbye.",
        "I've got to go now, see ya."
    ],

    "OOS": [
        "sing a song for me",
        "How do I implement multithreading in Go?",
        "open my email",
        "tell me a joke",
        "who is the president",
        "translate hello to french",
        "turn on the lights",
        "book a flight",
        "what time is it",
        "search for restaurants",
        "play a movie",
        "open youtube",
        "increase volume",
        "show my calendar",
        "what is machine learning",

        # Media & Entertainment
        "Tell me a fun fact about space.",
        "Can you put on a movie?",
        "Skip this song.",
        "Turn the volume up a bit.",
        "What's playing on the radio right now?",
        "Open YouTube and search for cat videos.",

        # Information
        "Explain the difference between Intel and AMD chips.",
        "When is the next bus heading to the University of Ottawa?",
        "Who won the Super Bowl last year?",
        "Tell me a fun fact about space.",
        "How do you spell 'exaggerate'?",
        "What is the capital of France?",
        "Search for the best pizza places nearby.",

        # Productivity & Apps
        "Check my emails from this morning.",
        "What's on my calendar for Tuesday?",
        "Open the calculator app.",
        "Send a text to Mom saying I'm running late.",
        "Write a new note called 'Grocery List'.",
        "Can you book a flight to New York?",

        # Smart Home (Non-timer/alarm)
        "Turn off the kitchen lights.",
        "Lock the front door.",
        "Set the thermostat to 72 degrees.",
        "Is the garage door closed?",

        # Translation & Language
        "How do you say 'where is the bathroom' in Spanish?",
        "Translate 'good morning' to Japanese.",

        # Complex/Abstract Questions
        "What is the meaning of life?",
        "Can you explain how machine learning works?",
        "Tell me a joke to make me laugh.",
        "What is the current price of Bitcoin?",
        "Who is the current President of the United States?",
        "How many miles are in a kilometer?",
        "Find me a recipe for chocolate cake."
    ],

    "Help": [
        "what can you do",
        "help me",
        "show me commands",
        "what are my options",
        "how does this game work",
        "what can i ask you",
        "give me instructions",
        "how do i play",
        "what actions are available",
        "show me how to use this",
        "i need help",
        "can you guide me",
        "what features do you have",
        "how does this system work",
        "what commands can i use"
    ],

    "Weather": [
        "what is the weather in Paris/B-city",
        "check the forecast for London/B-city",
        "tell me the weather in Tokyo/B-city",
        "how hot is it in Miami/B-city right now",
        "what is it like outside in Ottawa/B-city",
        "show me todays weather for Berlin/B-city",
        "give me the forecast for Madrid/B-city",
        "what is the temperature in Seattle/B-city",
        "how is the weather in Vancouver/B-city today",
        "can you check the weather for Dublin/B-city",
        "i want the weather report for Boston/B-city",
        "what will the weather be in Chicago/B-city",
        "tell me about the weather in Rome/B-city",
        "how warm is it in Lisbon/B-city",
        "what is going on weather wise in Cairo/B-city",
        "give me a weather update for Athens/B-city",
        "what is the forecast like in Prague/B-city",
        "can you look up the weather in Seoul/B-city",
        "what is the current weather in Dubai/B-city",
        "how does it feel outside in Delhi/B-city",
        "tell me the temperature in Phoenix/B-city",
        "check the weather for Denver/B-city",
        "i need the forecast for Halifax/B-city",
        "what is the weather report in Zurich/B-city",
        "can you tell me the weather in Moscow/B-city",
        "what is it like in Sydney/B-city today",
        "give me the latest weather for Nairobi/B-city",
        "how is the weather looking in Lagos/B-city",
        "what is the outlook for Havana/B-city",
        "show me the weather conditions in Manila/B-city",
        "what is the outlook for Havana/B-city",
        "show me the weather conditions in Manila/B-city",
        "tell me the weather in California/B-location right/B-time now/I-time",
        "check the forecast for Alaska/B-location tomorrow/B-time",
        "what is the weather like in Florida/B-location this/B-time evening/I-time",
        "give me the weather in Ontario/B-location next/B-time week/I-time",
        "show me the forecast for Texas/B-location this/B-time weekend/I-time",
        "tell me how it looks in Quebec/B-location tonight/B-time"
    ],

    "WeatherWind": [
        "what is the wind speed in Ottawa/B-city",
        "is it windy in Berlin/B-city",
        "tell me the wind conditions in Calgary/B-city",
        "how strong is the wind in Halifax/B-city",
        "check the breeze in Dublin/B-city",
        "is there a strong wind in Boston/B-city",
        "what are the gusts like in Lisbon/B-city",
        "give me the wind forecast for Denver/B-city",
        "is it breezy in Seattle/B-city today",
        "how hard is the wind blowing in Phoenix/B-city",
        "tell me if it is gusty in Reykjavik/B-city",
        "what is the wind doing in Rome/B-city",
        "do i have strong gusts in Madrid/B-city",
        "check if it is windy in Vancouver/B-city",
        "what is the breeze like in Tokyo/B-city",
        "is there much wind in Paris/B-city right now",
        "give me the wind report for Seoul/B-city",
        "how windy will it be in Dubai/B-city",
        "tell me the current wind speed in Athens/B-city",
        "is it blustery in Prague/B-city",
        "what are the gust conditions in Cairo/B-city",
        "check the wind for Zurich/B-city",
        "will it be breezy in Sydney/B-city",
        "how windy is it around Delhi/B-city",
        "tell me if there are gusts in Nairobi/B-city",
        "what is the wind speed in Lagos/B-city",
        "is it breezy in Havana/B-city",
        "check for wind in Manila/B-city",
        "do we have strong breeze in Moscow/B-city",
         "check for wind in Manila/B-city",
        "do we have strong breeze in Moscow/B-city",
        "how windy is it in California/B-location right/B-time now/I-time",
        "tell me the wind forecast for Alaska/B-location tomorrow/B-time",
        "is it going to be breezy in Florida/B-location this/B-time afternoon/I-time",
        "check the gusts in Ontario/B-location tonight/B-time",
        "what will the wind be like in Texas/B-location this/B-time weekend/I-time",
        "give me the breeze report for Quebec/B-location next/B-time week/I-time"
    ],

    "WeatherCondition": [
        "is it sunny in Miami/B-city",
        "is it cloudy in Seattle/B-city",
        "tell me the current conditions in Paris/B-city",
        "is it foggy in London/B-city",
        "what does the sky look like in Rome/B-city",
        "are conditions clear in Tokyo/B-city",
        "is it overcast in Berlin/B-city",
        "tell me the sky conditions in Ottawa/B-city",
        "is it stormy in Dublin/B-city",
        "what are conditions like in Boston/B-city",
        "check if it is clear in Lisbon/B-city",
        "is it gloomy in Prague/B-city today",
        "tell me whether it is sunny in Cairo/B-city",
        "are there clouds in Athens/B-city right now",
        "what is the weather condition in Seoul/B-city",
        "is it foggy in Dubai/B-city",
        "check if the skies are clear in Delhi/B-city",
        "tell me if it is cloudy in Phoenix/B-city",
        "what are the current conditions in Denver/B-city",
        "is it overcast in Halifax/B-city",
        "show me the sky conditions in Zurich/B-city",
        "is it bright and sunny in Sydney/B-city",
        "tell me if it is gloomy in Nairobi/B-city",
        "what does the sky look like in Lagos/B-city",
        "is it cloudy over Havana/B-city",
        "check whether it is clear in Manila/B-city",
        "tell me the conditions in Moscow/B-city",
        "is it stormy in Vancouver/B-city today",
        "what are conditions like in Calgary/B-city",
        "is it stormy in Vancouver/B-city today",
        "what are conditions like in Calgary/B-city",
        "what are the conditions in California/B-location right/B-time now/I-time",
        "tell me if the skies are clear in Alaska/B-location tomorrow/B-time",
        "is it cloudy in Florida/B-location this/B-time morning/I-time",
        "what will conditions be like in Ontario/B-location tonight/B-time",
        "check the sky conditions for Texas/B-location this/B-time weekend/I-time",
        "is it sunny in Quebec/B-location next/B-time week/I-time"
    ],

    "WeatherRain": [
       "will i need an umbrella in Dublin/B-city",
        "does it rain in Boston/B-city right now",
        "is there rain in Seattle/B-city today",
        "tell me if it is drizzling in London/B-city",
        "will it be rainy in Paris/B-city",
        "check for showers in Rome/B-city",
        "is there any rain in Ottawa/B-city",
        "am i going to get rain in Chicago/B-city",
        "are there showers in Berlin/B-city today",
        "is it pouring in Miami/B-city",
        "tell me if i need an umbrella in Lisbon/B-city",
        "will there be rain in Calgary/B-city",
        "is it a rainy day in Halifax/B-city",
        "check whether it is raining in Cairo/B-city",
        "is it drizzling in Tokyo/B-city",
        "will i need an umbrella in Seoul/B-city",
        "are there showers in Dubai/B-city",
        "is it raining in Delhi/B-city now",
        "check for rain in Phoenix/B-city",
        "will it be wet in Denver/B-city",
        "does Zurich/B-city have rain today",
        "is there a chance of showers in Sydney/B-city",
        "tell me if it is pouring in Nairobi/B-city",
        "is it rainy in Lagos/B-city",
        "will Havana/B-city get rain",
        "check if it is drizzling in Manila/B-city",
        "does Moscow/B-city need umbrellas today",
        "is there rain coming to Prague/B-city",
        "will Boston/B-city stay dry or rain",
        "is there rain coming to Prague/B-city",
        "will Boston/B-city stay dry or rain",
        "will it rain in California/B-location right/B-time now/I-time",
        "am i going to need an umbrella in Alaska/B-location tomorrow/B-time",
        "is there rain coming to Florida/B-location this/B-time evening/I-time",
        "check for showers in Ontario/B-location tonight/B-time",
        "will Texas/B-location get rain this/B-time weekend/I-time",
        "is it going to drizzle in Quebec/B-location next/B-time week/I-time"
    ],

    "WeatherSnow": [
       "will there be snow in Calgary/B-city",
        "does it snow in Oslo/B-city right now",
        "is there snow in Toronto/B-city today",
        "tell me if it is snowing in Ottawa/B-city",
        "are flurries falling in Winnipeg/B-city",
        "will i see snow in Edmonton/B-city",
        "check for snow in Reykjavik/B-city",
        "is it snowing in Denver/B-city",
        "will there be flurries in Prague/B-city",
        "check whether it is snowing in Moscow/B-city",
        "is snow falling in Helsinki/B-city",
        "tell me if there is snowfall in Zurich/B-city",
        "will it snow in Munich/B-city tonight",
        "is it snowy in Boston/B-city",
        "are there flurries in Stockholm/B-city",
        "check for snow in Minneapolis/B-city",
        "is it snowing in Sapporo/B-city",
        "tell me if it is snowing in Anchorage/B-city",
        "will there be snow in Fairbanks/B-city",
        "does Harbin/B-city have snow today",
        "is snow coming down in Krakow/B-city",
        "check for flurries in Geneva/B-city",
        "will Vienna/B-city get snow",
        "is it a snowy morning in Warsaw/B-city",
        "does Quebec/B-city have flurries right now",
        "tell me if Ulaanbaatar/B-city is getting snow",
        "will Reykjavik/B-city stay snowy today",
        "is there snowfall in Oslo/B-city tonight",
        "check if Montreal/B-city has flurries",
        "is there snowfall in Oslo/B-city tonight",
        "check if Montreal/B-city has flurries",
        "will it snow in Alaska/B-location right/B-time now/I-time",
        "is there snowfall in Ontario/B-location tomorrow/B-time",
        "check for flurries in Quebec/B-location this/B-time evening/I-time",
        "will Florida/B-location get snow this/B-time weekend/I-time",
        "is it going to snow in Colorado/B-location tonight/B-time",
        "tell me if there will be snow in Alberta/B-location next/B-time week/I-time"
    ],

    "Timer": [
    # Basic named timers
        "set a potato/B-name timer for 5/B-duration minutes/I-duration",
        "set timer for 10/B-duration minutes/I-duration called laundry/B-name",
        "start a pasta/B-name timer for 30/B-duration seconds/I-duration",
        "start timer for 2/B-duration hours/I-duration for the roast/B-name",
        "set a pizza/B-name timer for 45/B-duration minutes/I-duration",
        "egg/B-name timer for 15/B-duration minutes/I-duration",
        "set timer for 1/B-duration hour/I-duration labeled gym/B-name",
        "start a timer for 20/B-duration minutes/I-duration named study/B-name",
        "please set a tea/B-name timer for 3/B-duration hours/I-duration",
        "set timer for 90/B-duration seconds/I-duration for meditation/B-name",
        "set a 25/B-duration minute/I-duration cake/B-name timer",
        "oven/B-name timer for 40/B-duration minutes/I-duration",
        "start timer for 50/B-duration seconds/I-duration for the game/B-name",
        "set a timer for 6/B-duration hours/I-duration called sleep/B-name",
        "please start a workout/B-name timer for 12/B-duration minutes/I-duration",

        # Variations in phrasing and "fluff"
        "Can you put on a pizza/B-name timer for ten/B-duration minutes/I-duration please?",
        "I need a five/B-duration minute/I-duration nap/B-name countdown started now.",
        "Give me a 15/B-duration minute/I-duration shower/B-name timer.",
        "Hey, could you start a timer for 1/B-duration hour/I-duration and/I-duration 15/I-duration minutes/I-duration for the turkey/B-name?",
        "I'd like a chicken/B-name timer for 4/B-duration hours/I-duration.",

        # Written numbers vs. Digits
        "Timer for three/B-duration quarters/I-duration of/I-duration an/I-duration hour/I-duration for my break/B-name.",
        "Kick off a laundry/B-name timer for 12/B-duration minutes/I-duration.",
        "I need to time the plank/B-name for 60/B-duration seconds/I-duration.",
        "Go ahead and start a timer for 2/B-duration and/I-duration a/I-duration half/I-duration minutes/I-duration named boil/B-name.",
        "Let's do a 10/B-duration minute/I-duration focus/B-name timer.",

        # Different verbs and imperatives
        "Set a timer: 5/B-duration minutes/I-duration for the cookies/B-name.",
        "Time my run/B-name for 45/B-duration minutes/I-duration.",
        "Would you mind setting a timer for two/B-duration hours/I-duration called yardwork/B-name?",
        "Start counting down 15/B-duration seconds/I-duration for the start/B-name.",
        "Need a timer for 1/B-duration minute/I-duration for the microwave/B-name.",

        # Short/Abbreviated commands
        "Timer 20/B-duration mins/I-duration for beans/B-name.",
        "Set a 2/B-duration hour/I-duration grill/B-name timer.",
        "Start a timer for an/B-duration hour/I-duration called nap/B-name.",
        "Quick tea/B-name timer for 10/B-duration seconds/I-duration.",

        # Complex/Conversational
        "Create a timer for one/B-duration hour/I-duration and/I-duration twenty/I-duration minutes/I-duration for the dryer/B-name.",
        "I've got something in the oven, set a baking/B-name timer for 25/B-duration minutes/I-duration.",
        "Start a clock for 5/B-duration minutes/I-duration for the test/B-name.",
        "Run a timer for 120/B-duration seconds/I-duration for the drill/B-name.",
        "Remind me with a timer in 7/B-duration minutes/I-duration for the tea/B-name."
    ],
    
    "Alarm": [
        # Basic named and dated alarms
        "set a work/B-name alarm for 7/B-time am/I-time on Monday/B-day",
        "wake me at 6/B-time am/I-time this Tuesday/B-day for my flight/B-name",
        "set gym/B-name alarm for 8/B-time am/I-time next/B-day Friday/I-day",
        "wake me at 7/B-time 30/I-time am/I-time on Wednesday/B-day for school/B-name",
        "set an alarm at 9/B-time am/I-time tomorrow/B-day labeled doctor/B-name",
        "medicine/B-name alarm at 10/B-time pm/I-time every/B-day Sunday/I-day",
        "wake me at 6/B-time 45/I-time am/I-time on Thursday/B-day for the meeting/B-name",
        "set alarm for 5/B-time am/I-time called yoga/B-name for Saturday/B-day",
        "set an alarm for 11/B-time pm/I-time tonight/B-day named pill/B-name",
        "wake me at 8/B-time 15/I-time am/I-time on Monday/B-day for work/B-name",
        "alarm at 7/B-time am/I-time tomorrow/B-day for trash/B-name day",
        "set alarm at 6/B-time pm/I-time next/B-day Tuesday/I-day for the game/B-name",
        "wake me at 9/B-time am/I-time this/B-day Saturday/I-day for hiking/B-name",
        "set alarm for 10/B-time am/I-time called brunch/B-name for Sunday/B-day",
        "I need to wake up at 7/B-time am/I-time tomorrow/B-day for my commute/B-name",

        # Variations in phrasing and "fluff"
        "Can you set a laundry/B-name alarm for 6/B-time 30/I-time am/I-time next/B-day Monday/I-day?",
        "I need to be awake by 7/B-time am/I-time tomorrow/B-day for the interview/B-name.",
        "Could you put a workout/B-name alarm on for 8/B-time am/I-time this/B-day Friday/I-day?",
        "I've got a meeting/B-name, so set an alarm for 9/B-time 15/I-time am/I-time on Wednesday/B-day.",
        "Hey, wake me up at 6/B-time in/I-time the/I-time morning/I-time tomorrow/B-day for the trip/B-name.",

        # Written numbers and relative days
        "Set an alarm for seven/B-time thirty/I-time tomorrow/B-day morning/I-day for my run/B-name.",
        "Wake me at quarter/B-time past/I-time six/I-time am/I-time next/B-day Thursday/I-day for the sunrise/B-name.",
        "I need a shift/B-name alarm for eight/B-time o'clock/I-time on Saturday/B-day.",
        "Put a morning/B-name alarm for five/B-time am/I-time sharp this/B-day Sunday/I-day.",
        "Create a 10/B-time pm/I-time tonight/B-day alarm called medication/B-name.",

        # Short/Abbreviated commands
        "Work/B-name alarm 7/B-time am/I-time Monday/B-day.",
        "Set 6/B-time 15/I-time am/I-time tomorrow/B-day gym/B-name alarm.",
        "8/B-time am/I-time Sunday/B-day church/B-name alarm.",
        "New alarm: 10/B-time pm/I-time tonight/B-day for baking/B-name.",

        # Different verbs and imperatives
        "Alert me at 7/B-time 45/I-time am/I-time tomorrow/B-day for my appointment/B-name.",
        "Initialize a study/B-name alarm for 11/B-time pm/I-time this/B-day Friday/I-day.",
        "Get me up at 5/B-time 30/I-time am/I-time next/B-day Monday/I-day for work/B-name.",
        "Don't let me sleep past 6/B-time 30/I-time am/I-time tomorrow/B-day for the flight/B-name.",
        "I'd like to set a 7/B-time am/I-time alarm for Monday/B-day named office/B-name."
    ],



}

# Parsing Logic
def parse_example(sentence):
    tokens, slots = [], []
    for word in sentence.split():
        if "/" in word:
            token, slot = word.rsplit("/", 1)
            slot = slot.rstrip(".,?!:;")
        else:
            token, slot = word, "O"
        tokens.append(token)
        slots.append(slot)
    return tokens, slots

# Model Architecture (Must match core/m4_intent.py)
class JointIntentSlotModel(nn.Module):
    def __init__(self, num_intents, num_slots):
        super().__init__()
        self.encoder = AutoModel.from_pretrained("distilbert-base-uncased")
        hidden_size = self.encoder.config.hidden_size
        self.intent_classifier = nn.Sequential(
            nn.Linear(hidden_size, 256),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(256, num_intents)
        )
        self.slot_classifier = nn.Linear(hidden_size, num_slots)

    def forward(self, input_ids, attention_mask, intent_labels=None, slot_labels=None):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        sequence_output = outputs.last_hidden_state
        cls_output = sequence_output[:, 0]
        
        intent_logits = self.intent_classifier(cls_output)
        slot_logits = self.slot_classifier(sequence_output)
        
        loss = None
        if intent_labels is not None and slot_labels is not None:
            intent_loss_fn = nn.CrossEntropyLoss()
            slot_loss_fn = nn.CrossEntropyLoss(ignore_index=-100)
            intent_loss = intent_loss_fn(intent_logits, intent_labels)
            slot_loss = slot_loss_fn(slot_logits.view(-1, slot_logits.shape[-1]), slot_labels.view(-1))
            loss = intent_loss + slot_loss
            
        return loss, intent_logits, slot_logits

# Dataset Class
class JointDataset(Dataset):
    def __init__(self, encodings, slot_labels, intent_labels):
        self.encodings = encodings
        self.slot_labels = slot_labels
        self.intent_labels = intent_labels

    def __getitem__(self, idx):
        return {
            "input_ids": torch.tensor(self.encodings["input_ids"][idx]),
            "attention_mask": torch.tensor(self.encodings["attention_mask"][idx]),
            "slot_labels": torch.tensor(self.slot_labels[idx]),
            "intent_label": torch.tensor(self.intent_labels[idx]),
        }

    def __len__(self):
        return len(self.intent_labels)

if __name__ == "__main__":
    print("Preparing dataset and tokenizing...")
    all_tokens, all_slots, all_intents = [], [], []
    
    for intent_name, sentences in intent_data.items():
        if intent_name in EXCLUDED_INTENTS:
            continue
        for sentence in sentences:
            tokens, slots = parse_example(sentence)
            all_tokens.append(tokens)
            all_slots.append(slots)
            all_intents.append(intent_name)

    # Create Mappings
    unique_slots = sorted(list(set(s for seq in all_slots for s in seq)))
    slot2id = {s: i for i, s in enumerate(unique_slots)}
    
    unique_intents = sorted(list(set(all_intents)))
    intent2id = {s: i for i, s in enumerate(unique_intents)}
    
    intent_labels_ids = [intent2id[i] for i in all_intents]

    # Tokenize
    tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
    encodings = tokenizer(all_tokens, is_split_into_words=True, padding=True, truncation=True, max_length=16, return_tensors="pt")
    
    # Align labels for WordPiece Tokenizer
    aligned_slot_labels = []
    for i in range(len(all_tokens)):
        word_ids = encodings.word_ids(batch_index=i)
        previous_word_id = None
        label_ids = []
        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != previous_word_id:
                label_ids.append(slot2id[all_slots[i][word_id]])
            else:
                label_ids.append(-100)
            previous_word_id = word_id
        aligned_slot_labels.append(label_ids)

    dataset = JointDataset(encodings, aligned_slot_labels, intent_labels_ids)
    dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

    print("Building model and starting training...")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = JointIntentSlotModel(len(intent2id), len(slot2id)).to(device)
    optimizer = AdamW(model.parameters(), lr=5e-5)

    # Train
    model.train()
    for epoch in range(10):
        total_loss = 0
        for batch in dataloader:
            optimizer.zero_grad()
            
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            intent_labels = batch["intent_label"].to(device)
            slot_labels = batch["slot_labels"].to(device)

            loss, _, _ = model(input_ids, attention_mask, intent_labels, slot_labels)
            loss.backward()
            optimizer.step()
            
            total_loss += loss.item()
        print(f"Epoch {epoch+1}/10 Loss: {total_loss:.3f}")

    # Save Model and Mappings
    os.makedirs(MODEL_DIR, exist_ok=True)
    
    torch.save(model.state_dict(), os.path.join(MODEL_DIR, "joint_bert.pt"))
    with open(os.path.join(MODEL_DIR, "intent2id.json"), 'w') as f:
        json.dump(intent2id, f)
    with open(os.path.join(MODEL_DIR, "slot2id.json"), 'w') as f:
        json.dump(slot2id, f)
        
    print(f"\nModel and mappings saved to {MODEL_DIR} successfully!")
